
FROM maven:3.8.5-openjdk-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Runtime stage
FROM openjdk:21.0.5-jdk-slim
WORKDIR /app
COPY --from=build /app/target/JobPortal-0.0.1-SNAPSHOT.jar JobPortal.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","JobPortal.jar"]
